---
# Build for only keymap files
include:
  - board: corne_left
    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
  # uncomment this when needed
  # - board: corne_left
  #   shield: nice_view
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  #   artifact-name: corne_studio_left
  # - board: corne_left
  #   shield: settings_reset
  #snippet: zmk-usb-logging
